version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: congress_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: civiscope-backend 
    build: .
    ports:
      - "5050:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
